---
- hosts: all
  roles:
    - install-openvswitch
    - setup-l2-tunnels

- hosts: primary
  vars:
    nexus_interfaces: >
      {{ ci_node_interfaces }} +
      {{ routers|map('extract', connections, ['data', 'port'])|list }}
    nexus_config_op: "add"
  roles:
    - claim-some-vlans
    - config-nexus-vlans
