---
- hosts: all
  tasks:
    - stat:
        path: /home/jenkins
      register: st
    - stat:
        path: /home/jenkins/workspace
      register: st2
    - debug: msg="{{ st2 }}"
    - debug: msg="{{ st }}"

#- hosts: all
#  vars:
#    additional_pip_libraries:
#      - "ImcSdk==0.7.2"
#      - "cryptography===2.1.4"
#  roles:
#    - install-openvswitch
#    - setup-l2-tunnels
#    - install-additional-pip-libraries
#
#- hosts: primary
#  roles:
#    - claim-some-vlans
#    - clear-nexus-vlans
#    - requires-a-cimc-baremetal
#    - configure-vlan-for-baremetal
#    - configure-vlan-for-hosts
