---
- hosts: all
  roles:
    - install-openvswitch
    - setup-l2-tunnels

- hosts: primary
  vars:
    nexus_interfaces: "{{ ci_node_interfaces }}"
  roles:
    - claim-some-vlans
    - clear-nexus-vlans
