---
- hosts: all
  roles:
    - install-openvswitch
  tasks:
    - name: Create OVS bridge to represent ex-net
      command: ovs-vsctl add-br br-ex
      become: true

    - name: Create OVS bridge to represent phynet connected to ucsm
      command: ovs-vsctl add-br br-ucsmnet
      become: true

- hosts: primary
  roles:
    - claim-some-vlans
